name: GitHub Pipeline
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
